version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
  exclusions:
    presets:
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - unparam
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Zereker/socket

linters-settings:
  misspell:
    locale: US
