run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
        - errcheck

linters-settings:
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/Zereker/socket
